apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations.health.argoproj.io_Rollout: |
{{ .Values.rolloutHealthCheck | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-cm
    app.kubernetes.io/part-of: argocd
data:
  service.alertmanager: |
    targets:
      - alertmanager.monitoring.svc:9093
    insecureSkipVerify: true
  trigger.on-sync-succeeded: |
{{ .Values.notifications.triggerOnSyncSucceeded | indent 4 }}
  trigger.on-sync-failed: |
{{ .Values.notifications.triggerOnSyncFailed | indent 4 }}
  template.app-sync-succeeded-alert: |
{{ .Values.notifications.templateAppSyncSucceededAlert | indent 4 }}
  template.app-sync-failed-alert: |
{{ .Values.notifications.templateAppSyncFailedAlert | indent 4 }}
