apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: gitea-workflow-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: gitea-push
      eventSourceName: gitea-webhook
      eventName: gitea
  template:
    serviceAccountName: operate-workflow-sa
  triggers:
    - template:
        name: trigger-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: gitea-triggered-
                namespace: argo
              spec:
                workflowTemplateRef:
                  name: image-build-stub
